# Generated by Django 5.0.2 on 2024-02-16 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchapp', '0002_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
