# Generated by Django 5.0.2 on 2024-02-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchapp', '0005_remove_category_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(to='watchapp.product'),
        ),
    ]
