# Generated by Django 5.0.2 on 2024-02-17 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchapp', '0006_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
