# Generated by Django 5.0.2 on 2024-02-17 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchapp', '0008_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
