# Generated by Django 5.0.2 on 2024-05-24 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchapp', '0010_color_size_product_colors_product_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_colors/')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchapp.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchapp.product')),
            ],
        ),
    ]
