# Generated by Django 5.0.2 on 2024-05-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchapp', '0012_alter_product_colors_alter_productimage_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(to='watchapp.color'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
